/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flowersalessystem1;

import Classes.User;
import Databases.UserDatabaseManager;
import static Databases.UserDatabaseManager.getUsers;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author murat
 */
public class CustomerPage extends javax.swing.JFrame {

    /**
     * Creates new form Customers
     */
    DefaultTableModel t = new DefaultTableModel();
    private final JPanel patternPanel;

    public CustomerPage() {

        initComponents();
        patternPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Image patternImage = new ImageIcon("C:\\Users\\murat\\Desktop\\1-1Z3041506352H.jpg").getImage(); // Desenin yolunu belirtin
                g.drawImage(patternImage, 0, 0, getWidth(), getHeight(), null);
            }
        };
        patternPanel.setLayout(null);
        patternPanel.setBounds(0, 0, getWidth(), getHeight());
        getContentPane().add(patternPanel);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                patternPanel.setBounds(0, 0, getWidth(), getHeight());
            }
        });
        t.addColumn("name");
        t.addColumn("password");
        t.addColumn("email");
        updateTable();
    }

    public void updateTable() {
        // clear the table
        t.setRowCount(0);

        // get the list of users
        ArrayList<User> users = getUsers();

        // add each user to the table
        for (User user : users) {
            Object[] row = new Object[3];
            row[0] = user.getUsername();
            row[1] = user.getPassword();
            row[2] = user.getEmail();

            t.addRow(row);
        }

        // Update the JTable to reflect the added rows
        tblCustomer.setModel(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnBackMain = new javax.swing.JButton();
        txtDeletedCustomers = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCustomer.setBackground(new java.awt.Color(204, 204, 255));
        tblCustomer.setModel(t);
        jScrollPane2.setViewportView(tblCustomer);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("                     Customers");

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setText("Delete Customer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBackMain.setBackground(new java.awt.Color(204, 204, 255));
        btnBackMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackMain.setText("Back to Main");
        btnBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMainActionPerformed(evt);
            }
        });

        txtDeletedCustomers.setBackground(new java.awt.Color(204, 204, 255));
        txtDeletedCustomers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDeletedCustomers.setText("Show Deleted Customers");
        txtDeletedCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeletedCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDeletedCustomers)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDeletedCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomer.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a user first.");
        } else {
            String email = (String) tblCustomer.getValueAt(selectedRow, 1);
            User deletedUser = UserDatabaseManager.getUserByEmail(email);

            boolean isDeleted = UserDatabaseManager.deleteUser(email);

            if (isDeleted) {
                JOptionPane.showMessageDialog(null, "User deleted successfully");

                // Dosyaya silinen kullanıcının bilgilerini masaüstüne kaydetme
                String desktopPath = System.getProperty("user.home") + "/Desktop/";
                String fileName = desktopPath + "Deleted_customers.txt";
                try ( FileWriter writer = new FileWriter(fileName, true);  BufferedWriter bw = new BufferedWriter(writer);  PrintWriter pw = new PrintWriter(bw)) {
                    pw.println(deletedUser.getUsername() + "," + deletedUser.getEmail() + "," + deletedUser.getPassword());
                } catch (IOException e) {
                    e.printStackTrace();
                }

                updateTable(); // Deletion sonrasında tabloyu güncelle
            } else {
                JOptionPane.showMessageDialog(null, "An error occurred while deleting the user.");
            }
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMainActionPerformed
        // TODO add your handling code here:
        AdminPage a = new AdminPage();
        dispose();
        a.setVisible(true);

    }//GEN-LAST:event_btnBackMainActionPerformed

    private void txtDeletedCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeletedCustomersActionPerformed
        // TODO add your handling code here:

        t.setRowCount(0);

        String desktopPath = System.getProperty("user.home") + "/Desktop/";
        String fileName = desktopPath + "Deleted_customers.txt";

        try {
            FileReader fileReader = new FileReader(fileName);
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            String line;
            while ((line = bufferedReader.readLine()) != null) {
                String[] customerInfo = line.split(",");

                // Tabloya müşteri bilgilerini ekle
                Object[] row = new Object[3];
                row[0] = customerInfo[0]; // username
                row[1] = customerInfo[1]; // email
                row[2] = customerInfo[2]; // password
                t.addRow(row);
            }

            bufferedReader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Apply the updated table model to the table
        tblCustomer.setModel(t);


    }//GEN-LAST:event_txtDeletedCustomersActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMain;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JButton txtDeletedCustomers;
    // End of variables declaration//GEN-END:variables
}
